name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.8"
  PYTEST_ADDOPTS: "--capture=no --verbose"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]  # We can adjust the number of shards based on test count
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-shard pytest-sugar pytest-xdist

    - name: Build PyTorch
      run: |
        python setup.py develop

    - name: Run pytest tests
      env:
        PYTORCH_TEST_WITH_SLOW: 1
        PYTEST_SHARD: ${{ matrix.shard }}/4
      run: |
        pytest test/test_without_numpy_pytest.py \
          --shard ${{ matrix.shard }}/4 \
          -n auto \
          --dist loadscope \
          --junitxml=test-results/pytest-${{ matrix.shard }}.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: pytest-results-${{ matrix.shard }}
        path: test-results/

  # This job aggregates test results
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
    - name: Download test results
      uses: actions/download-artifact@v5
      with:
        path: test-results

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: "test-results/**/*.xml"
