name: PyTest Migration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest-cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/pytest/requirements-test.txt
          
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.1.0'
          
      - name: Run pytest CUDA tests
        run: |
          pytest tests/pytest/test_cuda/test_matmul.py -v \
            --durations=0 \
            --junitxml=test-results/junit.xml \
            --html=test-results/report.html \
            --self-contained-html
            
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-test-results-${{ matrix.python-version }}
          path: |
            test-results/
            
      - name: Report Test Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "PyTest Migration Test Results"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}