name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12"
  PYTEST_ADDOPTS: "--capture=no --verbose"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1]  # Since we're starting with just one test, we can use a single shard
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch pytest pytest-sugar pytest-xdist

    - name: Run pytest tests
      run: |
        pytest test/test_without_numpy_pytest.py \
          -n auto \
          --dist loadscope \
          --junitxml=test-results/pytest.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: test-results/

  # This job aggregates test results
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        path: test-results

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: "test-results/**/*.xml"